name: Upload Website

on:
  push:
    branches:
      - master

jobs:

  dupload_to_s3:
    runs-on: ubuntu-latest

    steps:
      - name: Upload index.html to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: |
          aws s3 cp index.html s3://github-action-dep/index.html --acl public-read --cache-control "max-age=0, no-cache, no-store, must-revalidate"
