name: Upload Website

on:
  push:
    branches:
      - master

jobs:
  upload_to_s3:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: brew install awscli

      - name: Upload index.html to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
        run: |
          ls -la
          aws s3 cp index.html s3://github-action-dep/index.html --acl public-read --cache-control"
